spring:
  application:
    name: user-service
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create                              # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs